@startuml

package "Visualization" #DDDDDD {
    !include App.puml
    !include Visualizer.puml
    !include SimulationParameters.puml
}

package "Simulation" {
       !include Compatibility.puml
}

Compatibility <-- App : Calls launchSkysim() <
SimulationParameters -- App

@enduml