@startuml
class Compatibility {
    +composeArgs(param: SimulationParameters): ArrayList<String>
    +launchSkysim(args: SimulationParameters): Channel<Generation>
}

Compatibility -- Skysim
@enduml